/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aplicativo.telas;

import com.aplicativo.controles.RepositoryManager;
import com.aplicativo.controles.RiscoController;
import com.aplicativo.entidades.Risco;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luis.assulfi
 */
public class TelaCadastroRiscos extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    private Risco risco;
    private TelaRelatorio telaRelatorio;
    
    /**
     * Creates new form TelaCadastroRiscos
     */
    private TelaCadastroRiscos() {
        initComponents();
    }
    
    public TelaCadastroRiscos(TelaPrincipal telaPrincipal){
        //Construtor padrão
        this();
        
        this.telaPrincipal = telaPrincipal;
        
    }
    
    public TelaCadastroRiscos(TelaRelatorio telaRelatorio, Risco r){
        
        this();
        this.telaRelatorio = telaRelatorio;
        this.risco = r;
        
        //Tornando visivel na tela os valores que serão editados
        jTextFieldObjetivo.setText(r.getObjetivo());
        jTextArea1.setText(r.getCausa());
        jTextFieldProcesso.setText(r.getProcesso());
        jTextFieldRisco.setText(r.getNomeRisco());
        jTextFieldConsequencia.setText(r.getConsequencia());
        
        switch(r.getNatureza()){
            case "Positivo":
                jRadioButtonNaturezaPositivo.setSelected(true);
            break;
            case "Negativo":
                jRadioButtonNaturezaNegativo.setSelected(true);
            break;
        }
        
        switch(r.getProbabilidadeRisco()){
            case 1:
                jRadioButton1.setSelected(true);
                break;
            case 2:
                jRadioButton2.setSelected(true);
                break;
            case 3:
                jRadioButton3.setSelected(true);
                break;
            case 4:
                jRadioButton4.setSelected(true);
                break;
            case 5:
                jRadioButton5.setSelected(true);
                break;
        }
        
        switch(r.getImpactoRisco()){
            case 1:
                jRadioButton6.setSelected(true);
            break;
            case 2:
                jRadioButton7.setSelected(true);
            break;
            case 3:
                jRadioButton8.setSelected(true);
            break;
            case 4:
                jRadioButton9.setSelected(true);
            break;
            case 5:
                jRadioButton10.setSelected(true);
            break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProcesso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldObjetivo = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRisco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldConsequencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonNaturezaPositivo = new javax.swing.JRadioButton();
        jRadioButtonNaturezaNegativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Identificação de riscos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Processo/ Atividade:");

        jLabel2.setText("Objetivo:");

        jTextFieldObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObjetivoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Cancelar");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel3.setText("Risco:");

        jLabel4.setText("Causa(s):");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Conseqüência:");

        jLabel6.setText("Natureza do risco:");

        buttonGroup1.add(jRadioButtonNaturezaPositivo);
        jRadioButtonNaturezaPositivo.setSelected(true);
        jRadioButtonNaturezaPositivo.setText("Positivo");

        buttonGroup1.add(jRadioButtonNaturezaNegativo);
        jRadioButtonNaturezaNegativo.setText("Negativo");

        jLabel7.setText("Probabilidade de ocorrência:");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("1");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("2");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("3");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("4");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("5");

        jLabel8.setText("Impacto do risco:");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("1");

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("2");

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("3");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("4");

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("5");

        jButtonCadastrar.setText("Salvar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProcesso))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldObjetivo)
                            .addComponent(jTextFieldRisco)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldConsequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonNaturezaPositivo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNaturezaNegativo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConsequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonNaturezaPositivo)
                    .addComponent(jRadioButtonNaturezaNegativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton6)
                        .addComponent(jRadioButton7)
                        .addComponent(jRadioButton8)
                        .addComponent(jRadioButton9)
                        .addComponent(jRadioButton10))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonCadastrar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      System.out.println("Método sair da tela de cadastro de riscos acionado");
      
      //Verificando qual tela está em segundo plano para atualizar
      if(this.telaPrincipal != null){
        //Configurar para habilitar a tela principal
        telaPrincipal.setEnabled(true);
        //Trazendo a tela principal para primeiro plano
        telaPrincipal.toFront();
      }
      
      if(this.telaRelatorio != null){
          //Configurar para habilitar a tela relatório
          telaRelatorio.setEnabled(true);
          //Trazendo a tela relatorio para primeiro plano
          telaRelatorio.toFront();
      }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.out.println("Clique no botão Cancelar");
        //Mata a tela atual
        this.dispose();
        //Verificando qual tela está em segundo plano para atualizar
        if (this.telaPrincipal != null) {
            //Trazendo a tela principal para 1º plano
            telaPrincipal.setEnabled(true);
        }
        
        if(this.telaRelatorio != null){
            telaRelatorio.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObjetivoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //Salvar dados
        System.out.println("Clique no botão salvar riscos");
        
        String processo = jTextFieldProcesso.getText();
        String objetivo = jTextFieldObjetivo.getText();
        String nomeRisco = jTextFieldRisco.getText();
        String causas = jTextArea1.getText();
        String consequencia = jTextFieldConsequencia.getText();
        String natureza ="";
        if (jRadioButtonNaturezaPositivo.isSelected()){
            natureza = "Positivo";
        } else if (jRadioButtonNaturezaNegativo.isSelected()){
            natureza = "Negativo";
        }
        int probabilidade = 0;
        if (jRadioButton1.isSelected()){
            probabilidade = 1;
        } else if (jRadioButton2.isSelected()){
            probabilidade = 2;
        } else if (jRadioButton3.isSelected()){
            probabilidade = 3;
        } else if (jRadioButton4.isSelected()){
            probabilidade = 4;
        } else if (jRadioButton5.isSelected()){
            probabilidade = 5;
        }
        int impacto = 0;
        if (jRadioButton6.isSelected()){
            impacto = 1;
        } else if (jRadioButton7.isSelected()){
            impacto = 2;
        } else if (jRadioButton8.isSelected()){
            impacto = 3;
        } else if (jRadioButton9.isSelected()){
            impacto = 4;
        } else if (jRadioButton10.isSelected()){
            impacto = 5;
        }
        
        int nivelDoRisco = impacto * probabilidade;
        
        //Criando a classe risco
        Risco r = this.risco;
    
        if (r == null){
            //criando o objeto risco
            r = new Risco(null,
            processo,
            objetivo,
            nomeRisco,
            causas,
            consequencia,
            natureza,
            probabilidade,
            impacto,
            nivelDoRisco,
            null,
            null,
            null,
            null,
            0,
            0,
            0);
        } else {
            //Atualiza os dados
            r.setCausa(causas);
            r.setConsequencia(consequencia);
            r.setNomeRisco(nomeRisco);
            r.setImpactoRisco(impacto);
            r.setNatureza(natureza);
            r.setProbabilidadeRisco(probabilidade);
            r.setProcesso(processo);
            r.setObjetivo(objetivo);
            r.setNivelDoRisco(nivelDoRisco);
        }
        
        //Chama o controller para tentar cadastrar
        RiscoController controller = new RiscoController();
        if(this.risco == null){
            //Tentar cadastrar novo
            if(controller.cadastrarRisco(r)){
                JOptionPane.showMessageDialog(this, "Risco cadastrado!");
                System.out.println("Risco cadastrado com sucesso! Fechando tela");
                this.dispose();
                this.telaPrincipal.toFront();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar! "
                        + "Verifique os dados!");
            }
        } else {
            //Tentar atualizar
            if(controller.atualizarRiscos(r)){
                JOptionPane.showMessageDialog(this, "Risco atualizado!");
                System.out.println("Risco atualizado com sucesso!");
                if(this.telaRelatorio != null){
                    System.out.println("Tenta atualizar tela");
                    this.telaRelatorio.atualizarModelo();
                }
                this.dispose();
                telaRelatorio.toFront();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar tabela!"
                        + " Verifique os dados!"); 
            }
        }
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroRiscos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButtonNaturezaNegativo;
    private javax.swing.JRadioButton jRadioButtonNaturezaPositivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldConsequencia;
    private javax.swing.JTextField jTextFieldObjetivo;
    private javax.swing.JTextField jTextFieldProcesso;
    private javax.swing.JTextField jTextFieldRisco;
    // End of variables declaration//GEN-END:variables
}
